name: Supabase Keep-Alive Ping

on:
  schedule:
    - cron: '0 1 * * 1,4'  # Runs every Monday and Thursday
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Make an API request to Supabase
        run: |
          curl -L -X POST '${{secrets.FUNCTION_URL}}' \
                -H 'Authorization: Bearer ${{secrets.BEARER_TOKEN}}' \
                -H 'Content-Type: application/json'
